# This config defines

fragment_program:
  vertex_shader: "lines_instanced_positions.vs.glsl"
  fragment_shader: "fragment_picking/frag_map.fs.glsl"
  extra_definitions:
    smooth_shading: 1
    texture: 0
    face_color: 0
    instanced: 0

